export const ALL_MESSAGES_SUCCESS = 'ALL_MESSAGES_SUCCESS';
export const MESSAGES_LOADING ='MESSAGES_LOADING';

export const SET_USER_NAME = 'SET_USER_NAME';

export const SEND_MESSAGE = 'SEND_MESSAGE';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
